import {
  Wrench,
  Zap,
  Paintbrush,
  Sparkles,
  Leaf,
  Key,
  Hammer,
  Ruler,
  BrickWall,
  Grid,
  PanelsTopLeft,
  Snowflake,
  Flame,
  Plug,
  Network,
  SatelliteDish,
  PanelsRightBottom,
  Home,
  Anvil,
  Truck,
  Bug,
  PanelLeftOpen,
  Package,
  ChefHat,
  ShowerHead,
  Sun,
  Square,
  Wallpaper,
  Shield,
  Puzzle,
  CircleHelp,
  type LucideIcon,
} from "lucide-react";

export const SERVICE_ICON_BY_SLUG: Record<string, LucideIcon> = {
  plomberie: Wrench,
  electricite: Zap,
  peinture: Paintbrush,
  nettoyage: Sparkles,
  jardinage: Leaf,
  serrurerie: Key,
  "menuiserie-bois": Hammer,
  "aluminium-pvc": Ruler,
  maconnerie: BrickWall,
  carrelage: Grid,
  platrerie: PanelsTopLeft,
  climatisation: Snowflake,
  "chauffe-eau": Flame,
  "reparation-electromenager": Plug,
  "informatique-reseaux": Network,
  "parabole-tv": SatelliteDish,
  vitrerie: PanelsRightBottom,
  "toiture-etancheite": Home,
  ferronnerie: Anvil,
  demenagement: Truck,
  "traitement-nuisibles": Bug,
  "rideaux-stores": PanelLeftOpen,
  "montage-meubles": Package,
  "cuisines-placards": ChefHat,
  "salle-de-bain": ShowerHead,
  solaire: Sun,
  "sols-parquet": Square,
  "papier-peint": Wallpaper,
  "securite-alarme": Shield,
  "multi-services": Puzzle,
};

export function getServiceIcon(slug: string): LucideIcon {
  return SERVICE_ICON_BY_SLUG[slug] ?? CircleHelp;
}

