global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090", "172.17.0.1:2102"]

  - job_name: "cadvisor"
    static_configs:
      - targets:
          - cadvisor:8080

  - job_name: "node_exporter"
    static_configs:
      - targets:
          - node_exporter:9100
