services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: khadamat
      POSTGRES_PASSWORD: khadamat
      POSTGRES_DB: khadamat
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
      DATABASE_URL: "postgresql://khadamat:khadamat@db:5432/khadamat?schema=public"
      FORCE_ONLINE: "true"
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/workspace/backend
      - /workspace/backend/node_modules

volumes:
  dbdata:
