version: '3.8'
services:
  api:
    build: .
    env_file:
      - .env.online.staging
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:7
    restart: unless-stopped
volumes:
  db_data:
