version: '3.8'
services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:7
    restart: unless-stopped
  clamav:
    image: clamav/clamav:latest
    restart: unless-stopped
    ports:
      - "3310:3310"
volumes:
  db_data:
