INSERT INTO "City" ("id","name","slug","lat","lng","country") VALUES (1, 'Casablanca', 'casablanca', 33.5731, -7.5898, 'MA');
INSERT INTO "City" ("id","name","slug","lat","lng","country") VALUES (2, 'Rabat', 'rabat', 34.0209, -6.8416, 'MA');
INSERT INTO "City" ("id","name","slug","lat","lng","country") VALUES (3, 'Marrakech', 'marrakech', 31.6295, -7.9811, 'MA');
INSERT INTO "City" ("id","name","slug","lat","lng","country") VALUES (4, 'Fès', 'fes', 34.0181, -5.0078, 'MA');
INSERT INTO "City" ("id","name","slug","lat","lng","country") VALUES (5, 'Tanger', 'tanger', 35.7595, -5.834, 'MA');
INSERT INTO "City" ("id","name","slug","lat","lng","country") VALUES (6, 'Agadir', 'agadir', 30.4278, -9.5981, 'MA');
INSERT INTO "City" ("id","name","slug","lat","lng","country") VALUES (7, 'Kénitra', 'kenitra', 34.261, -6.5802, 'MA');
INSERT INTO "City" ("id","name","slug","lat","lng","country") VALUES (8, 'Oujda', 'oujda', 34.6814, -1.9086, 'MA');
INSERT INTO "City" ("id","name","slug","lat","lng","country") VALUES (9, 'Meknès', 'meknes', 33.895, -5.5547, 'MA');
INSERT INTO "City" ("id","name","slug","lat","lng","country") VALUES (10, 'Tétouan', 'tetouan', 35.5785, -5.3684, 'MA');
INSERT INTO "City" ("id","name","slug","lat","lng","country") VALUES (11, 'Safi', 'safi', 32.2994, -9.2372, 'MA');
INSERT INTO "ServiceCatalog" ("id","code","slug","name_fr","name_ar","category_code","is_active","sort_order") VALUES (1, 'PLOMBERIE', 'plomberie', 'Plomberie', 'السباكة', 'PLOMBERIE', true, 1);
INSERT INTO "ServiceCatalog" ("id","code","slug","name_fr","name_ar","category_code","is_active","sort_order") VALUES (2, 'ELECTRICITE', 'electricite', 'Électricité', 'الكهرباء', 'ELECTRICITE', true, 2);
INSERT INTO "ServiceCatalog" ("id","code","slug","name_fr","name_ar","category_code","is_active","sort_order") VALUES (3, 'PEINTURE', 'peinture', 'Peinture', 'الصباغة', 'PEINTURE', true, 3);
INSERT INTO "ServiceCatalog" ("id","code","slug","name_fr","name_ar","category_code","is_active","sort_order") VALUES (4, 'NETTOYAGE', 'nettoyage', 'Nettoyage (ménage)', 'التنظيف المنزلي', 'NETTOYAGE', true, 4);
INSERT INTO "ServiceCatalog" ("id","code","slug","name_fr","name_ar","category_code","is_active","sort_order") VALUES (5, 'JARDINAGE', 'jardinage', 'Jardinage', 'البستنة', 'JARDINAGE', true, 5);
INSERT INTO "ServiceCatalog" ("id","code","slug","name_fr","name_ar","category_code","is_active","sort_order") VALUES (6, 'SERRURERIE', 'serrurerie', 'Serrurerie', 'خدمات الأقفال', 'SERRURERIE', true, 6);
INSERT INTO "ServiceCatalog" ("id","code","slug","name_fr","name_ar","category_code","is_active","sort_order") VALUES (7, 'MENUISERIE_BOIS', 'menuiserie-bois', 'Menuiserie bois', 'نجارة الخشب', 'MENUISERIE_BOIS', true, 7);
INSERT INTO "ServiceCatalog" ("id","code","slug","name_fr","name_ar","category_code","is_active","sort_order") VALUES (8, 'ALU_PVC', 'aluminium-pvc', 'Aluminium / PVC', 'ألمنيوم وPVC', 'ALU_PVC', true, 8);
INSERT INTO "ServiceCatalog" ("id","code","slug","name_fr","name_ar","category_code","is_active","sort_order") VALUES (9, 'MACONNERIE', 'maconnerie', 'Maçonnerie', 'أشغال البناء', 'MACONNERIE', true, 9);
INSERT INTO "ServiceCatalog" ("id","code","slug","name_fr","name_ar","category_code","is_active","sort_order") VALUES (10, 'CARRELAGE', 'carrelage', 'Carrelage / Faïence', 'تبليط / سيراميك', 'CARRELAGE', true, 10);
INSERT INTO "ServiceCatalog" ("id","code","slug","name_fr","name_ar","category_code","is_active","sort_order") VALUES (11, 'PLATRERIE', 'platrerie', 'Plâtrerie / Faux plafonds', 'الجبس والأسقف المعلقة', 'PLATRERIE', true, 11);
INSERT INTO "ServiceCatalog" ("id","code","slug","name_fr","name_ar","category_code","is_active","sort_order") VALUES (12, 'CLIM_CHAUFFAGE', 'climatisation', 'Climatisation / Chauffage', 'التكييف والتدفئة', 'CLIM_CHAUFFAGE', true, 12);
INSERT INTO "ServiceCatalog" ("id","code","slug","name_fr","name_ar","category_code","is_active","sort_order") VALUES (13, 'CHAUFFE_EAU', 'chauffe-eau', 'Chauffe-eau (gaz/élec)', 'سخان الماء (غاز/كهرباء)', 'CHAUFFE_EAU', true, 13);
INSERT INTO "ServiceCatalog" ("id","code","slug","name_fr","name_ar","category_code","is_active","sort_order") VALUES (14, 'ELECTROMENAGER', 'reparation-electromenager', 'Réparation électroménager', 'إصلاح الأجهزة المنزلية', 'ELECTROMENAGER', true, 14);
INSERT INTO "ServiceCatalog" ("id","code","slug","name_fr","name_ar","category_code","is_active","sort_order") VALUES (15, 'INFORMATIQUE', 'informatique-reseaux', 'Informatique / Réseaux', 'معلوميات وشبكات', 'INFORMATIQUE', true, 15);
INSERT INTO "ServiceCatalog" ("id","code","slug","name_fr","name_ar","category_code","is_active","sort_order") VALUES (16, 'PARABOLE_TV', 'parabole-tv', 'Parabole / TV', 'تركيب الصحون اللاقطة / التلفاز', 'PARABOLE_TV', true, 16);
INSERT INTO "ServiceCatalog" ("id","code","slug","name_fr","name_ar","category_code","is_active","sort_order") VALUES (17, 'VITRERIE', 'vitrerie', 'Vitrerie', 'الزجاج', 'VITRERIE', true, 17);
INSERT INTO "ServiceCatalog" ("id","code","slug","name_fr","name_ar","category_code","is_active","sort_order") VALUES (18, 'TOITURE_ETANCHEITE', 'toiture-etancheite', 'Toiture / Étanchéité', 'الأسطح والعزل المائي', 'TOITURE_ETANCHEITE', true, 18);
INSERT INTO "ServiceCatalog" ("id","code","slug","name_fr","name_ar","category_code","is_active","sort_order") VALUES (19, 'FERRONNERIE', 'ferronnerie', 'Ferronnerie', 'الحدادة', 'FERRONNERIE', true, 19);
INSERT INTO "ServiceCatalog" ("id","code","slug","name_fr","name_ar","category_code","is_active","sort_order") VALUES (20, 'DEMENAGEMENT', 'demenagement', 'Déménagement', 'نقل الأثاث', 'DEMENAGEMENT', true, 20);
INSERT INTO "ServiceCatalog" ("id","code","slug","name_fr","name_ar","category_code","is_active","sort_order") VALUES (21, 'NUISIBLES', 'traitement-nuisibles', 'Traitement nuisibles', 'مكافحة الحشرات', 'NUISIBLES', true, 21);
INSERT INTO "ServiceCatalog" ("id","code","slug","name_fr","name_ar","category_code","is_active","sort_order") VALUES (22, 'RIDEAUX_STORES', 'rideaux-stores', 'Pose rideaux / stores', 'تركيب الستائر والستائر المتحركة', 'RIDEAUX_STORES', true, 22);
INSERT INTO "ServiceCatalog" ("id","code","slug","name_fr","name_ar","category_code","is_active","sort_order") VALUES (23, 'MONTAGE_MEUBLES', 'montage-meubles', 'Montage meubles', 'تركيب الأثاث', 'MONTAGE_MEUBLES', true, 23);
INSERT INTO "ServiceCatalog" ("id","code","slug","name_fr","name_ar","category_code","is_active","sort_order") VALUES (24, 'CUISINES_PLACARDS', 'cuisines-placards', 'Cuisines / Placards', 'مطابخ وخزائن', 'CUISINES_PLACARDS', true, 24);
INSERT INTO "ServiceCatalog" ("id","code","slug","name_fr","name_ar","category_code","is_active","sort_order") VALUES (25, 'SALLE_DE_BAIN', 'salle-de-bain', 'Salle de bain (installation)', 'تركيب الحمامات', 'SALLE_DE_BAIN', true, 25);
INSERT INTO "ServiceCatalog" ("id","code","slug","name_fr","name_ar","category_code","is_active","sort_order") VALUES (26, 'SOLAIRE', 'solaire', 'Solaire (photovoltaïque)', 'طاقة شمسية (ألواح)', 'SOLAIRE', true, 26);
INSERT INTO "ServiceCatalog" ("id","code","slug","name_fr","name_ar","category_code","is_active","sort_order") VALUES (27, 'SOLS_PARQUET', 'sols-parquet', 'Sols / Parquet', 'الأرضيات والباركيه', 'SOLS_PARQUET', true, 27);
INSERT INTO "ServiceCatalog" ("id","code","slug","name_fr","name_ar","category_code","is_active","sort_order") VALUES (28, 'PAPIER_PEINT', 'papier-peint', 'Papier peint / Tapisserie', 'ورق الجدران والتنجيد', 'PAPIER_PEINT', true, 28);
INSERT INTO "ServiceCatalog" ("id","code","slug","name_fr","name_ar","category_code","is_active","sort_order") VALUES (29, 'SECURITE_CCTV', 'securite-alarme', 'Sécurité / Alarme / CCTV', 'الأمن والمراقبة (كاميرات وإنذار)', 'SECURITE_CCTV', true, 29);
INSERT INTO "ServiceCatalog" ("id","code","slug","name_fr","name_ar","category_code","is_active","sort_order") VALUES (30, 'MULTI_SERVICES', 'multi-services', 'Multi-services (petits travaux)', 'أشغال منزلية عامة', 'MULTI_SERVICES', true, 30);
