import { createContext, useContext, useState, useEffect } from "react";

type Language = "fr" | "ar";

interface LanguageContextType {
  language: Language;
  toggleLanguage: () => void;
  t: (key: string, options?: { count?: number; formattedCount?: string }) => string;
  isRTL: boolean;
}

type TranslationDict = Record<string, string | Record<string, string>>;

const translations: Record<Language, TranslationDict> = {
  fr: {
    // Navigation
    "nav.home": "Accueil",
    "nav.services": "Services",
    "nav.providers": "Prestataires",
    "nav.club_pro": "Club Pro",
    "nav.messages": "Messages",
    "nav.project": "Projets",
    "nav.support": "Support",
    "nav.login": "Connexion",
    "nav.register": "Inscription",
    "nav.contact": "Contact",
    "nav.about": "À propos",
    "nav.profile": "Profil",
    
    // User Profile Menu
    "profile.menu.profile": "Profil",
    "profile.menu.orders": "Mes commandes",
    "profile.menu.reservations": "Mes réservations",
    "profile.menu.favorites": "Mes favoris",
    "profile.menu.missions": "Mes missions",
    "profile.menu.club_pro": "Club Pro",
    "profile.menu.messages": "Messages",
    "profile.menu.settings": "Réglages",
    "profile.menu.logout": "Se déconnecter",
    "profile.role.client": "Client",
    "profile.role.provider": "Prestataire",
    
    // Hero section
    "hero.title": "Trouvez le bon",
    "hero.title_highlight": "prestataire",
    "hero.subtitle": "La première plateforme marocaine qui connecte clients et prestataires de services professionnels",
    "hero.search_placeholder": "Que recherchez-vous ? (ex: plombier, électricien...)",
    "hero.search_button": "Rechercher",
    "hero.location": "Casablanca",
    "hero.city_placeholder": "Ville (ex: Casablanca, Rabat...)",
    "hero.provider_placeholder": "Rechercher un prestataire spécifique (optionnel)",
    
    // Services
    "services.title": "Nos services populaires",
    "services.subtitle": "Découvrez notre large gamme de services professionnels disponibles dans tout le Maroc",
    "services.explore": "Explorer",
    "services.popular": "Services Populaires",
    "services.popular_in": "Services populaires à",
    "services.plumbing": "Plomberie",
    "services.electricity": "Électricité",
    "services.cleaning": "Ménage",
    "services.gardening": "Jardinage",
    "services.painting": "Peinture",
    "services.repair": "Réparation",
    "services.installation": "Installation",
    "services.deep_cleaning": "Nettoyage approfondi",
    "services.moving": "Déménagement",
    "services.providers_count": {
      one: "{{count}} prestataire",
      other: "{{count}} prestataires"
    },
    
    // How it works
    "how_it_works.title": "Comment ça marche ?",
    "how_it_works.subtitle": "Trouvez le bon prestataire en 3 étapes simples",
    "how_it_works.step1": "1. Recherchez",
    "how_it_works.step1_desc": "Décrivez votre besoin. Indiquez votre localisation. On s'occupe du reste.",
    "how_it_works.step2": "2. Comparez",
    "how_it_works.step2_desc": "Comparez les profils. Lisez les avis. Choisissez le bon prestataire.",
    "how_it_works.step3": "3. Contactez",
    "how_it_works.step3_desc": "Contactez directement. Discutez des détails. Planifiez votre service.",
    
    // Providers
    "providers.title": "Prestataires Vérifiés",
    "providers.subtitle": "Découvrez nos prestataires Club Pro vérifiés et hautement qualifiés",
    "providers.club_pro_badge": "Club Pro Vérifié",
    "providers.online": "En ligne",
    "providers.contact": "Contacter",
    "providers.reviews": "avis",
    "providers.view_profile": "Profil",
    
    // Chat
    "chat.title": "Messagerie Instantanée",
    "chat.subtitle": "Communiquez directement avec vos prestataires grâce à notre système de messagerie temps réel avec appels audio et vidéo intégrés.",
    "chat.features.realtime": "Messages en temps réel",
    "chat.features.calls": "Appels audio et vidéo",
    "chat.features.files": "Partage de fichiers sécurisé",
    "chat.input_placeholder": "Tapez votre message...",
    
    // Club Pro
    "club_pro.title": "Rejoignez l'Élite des Prestataires",
    "club_pro.subtitle": "Accédez à des fonctionnalités premium et augmentez votre visibilité avec notre programme Club Pro vérifié",
    "club_pro.home_subtitle": "Accédez aux projets de grandes ampleurs et bénéficiez d'avantages exclusifs pour seulement 50 DH/mois.",
    "club_pro.cta": "Devenir Club Pro",
    "club_pro.join_cta": "Devenir Club Pro - 50 DH/mois",
    "club_pro.badge_benefit": "Badge Club Pro pour se démarquer",
    "club_pro.priority_benefit": "Priorité dans les résultats de recherche",
    "club_pro.support_benefit": "Support dédié aux prestataires Club Pro",
    "club_pro.exclusive_access": "🏆 ACCÈS EXCLUSIF",
    "club_pro.large_projects": "Projets de grandes ampleurs réservés aux Club Pro",
    "club_pro.verification.title": "Vérification Complète",
    "club_pro.verification.desc": "Documents professionnels vérifiés : patente, RC, assurance et reconnaissance faciale",
    "club_pro.visibility.title": "Visibilité Premium",
    "club_pro.visibility.desc": "Apparaissez en tête des résultats de recherche avec un badge Club Pro distinctif",
    "club_pro.trust.title": "Confiance Renforcée",
    "club_pro.trust.desc": "Gagnez la confiance des clients avec votre statut vérifié et vos garanties étendues",
    "club_pro.verification_24h": "Vérification en 24h",
    "club_pro.priority_support": "Support prioritaire",
    "club_pro.premium_badge": "Badge premium",
    "club_pro.why_choose": "Pourquoi Choisir Club Pro ?",
    "club_pro.join_elite": "Rejoignez l'élite des prestataires et multipliez vos opportunités",
    "club_pro.benefit_badge_title": "Badge Club Pro Distinctif",
    "club_pro.benefit_badge_desc": "Votre profil sera marqué d'un badge premium visible par tous les clients",
    "club_pro.benefit_ranking_title": "Classement Prioritaire",
    "club_pro.benefit_ranking_desc": "Apparaissez en premier dans les résultats de recherche",
    "club_pro.benefit_projects_title": "Accès aux Projets Premium",
    "club_pro.benefit_projects_desc": "Recevez les demandes de projets les plus valorisés",
    "club_pro.benefit_support_title": "Support Client Prioritaire",
    "club_pro.benefit_support_desc": "Assistance dédiée et temps de réponse accéléré",
      "club_pro.pricing_title": "Un seul abonnement, tous les avantages",
      "club_pro.pricing_subtitle": "Rejoignez le Club Pro et accédez aux plus grands projets",
      "club_pro.per_month": "par mois",
      "club_pro.commitment_1_year": "Engagement 1 an",
      "club_pro.join_button": "Rejoindre le Club Pro",
      "club_pro.payment_methods": "Moyens de paiement acceptés",
      "club_pro.benefits_title": "Vos Avantages Exclusifs",
      "club_pro.benefits_subtitle": "Découvrez tous les bénéfices réservés aux membres Club Pro",
      "club_pro.benefits.badge.title": "Badge Vérifié",
      "club_pro.benefits.badge.desc": "Profil certifié avec badge orange",
      "club_pro.benefits.badge.highlight": "Exclusif",
      "club_pro.benefits.ranking.title": "Classement Prioritaire",
      "club_pro.benefits.ranking.desc": "Premier dans les résultats de recherche",
      "club_pro.benefits.ranking.highlight": "Premium",
      "club_pro.benefits.clients.title": "Clients Premium",
      "club_pro.benefits.clients.desc": "Accès aux clients les plus valorisés",
      "club_pro.benefits.clients.highlight": "Exclusif",
      "club_pro.benefits.support.title": "Support Dédié",
      "club_pro.benefits.support.desc": "Réponse garantie en moins d'1 heure",
      "club_pro.benefits.support.highlight": "24/7",
      "club_pro.benefits.reservations.title": "Réservations Avancées",
      "club_pro.benefits.reservations.desc": "Planification et gestion optimisée",
      "club_pro.benefits.reservations.highlight": "Smart",
      "club_pro.benefits.pricing.title": "Tarifs Premium",
      "club_pro.benefits.pricing.desc": "Prix plus élevés pour vos services",
      "club_pro.benefits.pricing.highlight": "+40%",
      "club_pro.stats.more_clients": "Plus de clients",
      "club_pro.stats.revenue_increase": "Augmentation CA",
      "club_pro.stats.priority_support": "Support prioritaire",
      "club_pro.stats.satisfaction": "Satisfaction",
      "club_pro.simple_pricing_title": "Tarification Simple",
      "club_pro.simple_pricing_desc": "Un seul plan, tous les avantages inclus",
      "club_pro.commitment_secure": "Engagement d'un an - Paiement sécurisé",
      "club_pro.join_now": "Rejoindre maintenant",
      "club_pro.secure_payment": "Paiement sécurisé - Carte bancaire, PayPal, Orange Money",
      "club_pro.testimonials_title": "Ils ont transformé leur activité",
      "club_pro.testimonials_subtitle": "Découvrez les témoignages de nos prestataires Club Pro",
      "club_pro.testimonials.ahmed.role": "Électricien Club Pro",
      "club_pro.testimonials.ahmed.text": "Depuis que j'ai rejoint le Club Pro, j'ai 3x plus de clients. Le badge vérifié fait toute la différence !",
      "club_pro.testimonials.ahmed.highlight": "+300% clients",
      "club_pro.testimonials.fatima.role": "Nettoyage Club Pro",
      "club_pro.testimonials.fatima.text": "Le support prioritaire est exceptionnel. Je reçois une réponse en moins d'1h à chaque fois !",
      "club_pro.testimonials.fatima.highlight": "Support 24/7",
      "club_pro.testimonials.mohammed.role": "Plombier Club Pro",
      "club_pro.testimonials.mohammed.text": "Apparaître en premier dans les résultats de recherche a boosté mon activité de 200% !",
      "club_pro.testimonials.mohammed.highlight": "+200% CA",
      "club_pro.cta_title": "Prêt à rejoindre l'élite ?",
      "club_pro.cta_subtitle": "Rejoignez le Club Pro et transformez votre activité dès aujourd'hui",
      "club_pro.cta_join": "Rejoindre le Club Pro",
      "club_pro.cta_learn_more": "En savoir plus",
      "club_pro.cta_features": "✓ Vérification en 24h • ✓ Support prioritaire • ✓ Sans engagement",
    
    // Project page
    "project.hero.badge": "Publier un Projet",
    "project.hero.find_the": "Trouvez le",
    "project.hero.ideal_provider": "Prestataire Idéal",
    "project.hero.description": "Décrivez votre projet et recevez des propositions de prestataires qualifiés. Comparez les offres et choisissez le meilleur professionnel pour vos besoins.",
    "project.form.title": "Publier un Nouveau Projet",
    "project.form.project_title": "Titre du Projet",
    "project.form.title_placeholder": "Ex: Installation électrique dans salon",
    "project.form.category": "Catégorie",
    "project.form.category_placeholder": "Choisir une catégorie",
    "project.form.budget": "Budget",
    "project.form.budget_placeholder": "Sélectionner le budget",
    "project.form.location": "Localisation",
    "project.form.location_placeholder": "Ex: Casablanca, Maarif",
    "project.form.deadline": "Délai souhaité",
    "project.form.deadline_placeholder": "Ex: Dans la semaine, Urgent",
    "project.form.description": "Description détaillée",
    "project.form.description_placeholder": "Décrivez votre projet en détail : travaux à effectuer, contraintes, matériel fourni ou non...",
    "project.form.skills": "Compétences recherchées",
    "project.form.skills_placeholder": "Ex: Électricien certifié, expérience domotique",
    "project.form.publishing": "Publication...",
    "project.form.publish_button": "Publier le Projet",
    "project.form.other": "Autre",
    "project.budget.under_500": "Moins de 500 DH",
    "project.budget.500_1000": "500 - 1000 DH",
    "project.budget.1000_2000": "1000 - 2000 DH",
    "project.budget.2000_5000": "2000 - 5000 DH",
    "project.budget.over_5000": "Plus de 5000 DH",
    "project.budget.negotiable": "À négocier",
    "project.toast.success_title": "Projet publié !",
    "project.toast.success_description": "Votre projet a été publié avec succès. Les prestataires vont recevoir des notifications.",
    "project.toast.error_title": "Erreur de publication",
    "project.toast.error_description": "Une erreur s'est produite lors de la publication.",
    "project.how_it_works.title": "Comment ça marche ?",
    "project.how_it_works.step1_title": "Publiez votre projet",
    
    // Search and filters
    "search.suggestions": "Suggestions",
    "search.clear_filters": "Effacer les filtres",
    "search.active_filters": "Filtres actifs",
    "search.search_term": "Recherche",
    "search.service": "Service",
    "search.city": "Ville",
    "search.price": "Prix",
    "search.available": "Disponible",
    "search.club_pro": "Club Pro",
    "search.date": "Date",
    "calendar.available": "Disponible",
    "calendar.unavailable": "Indisponible",
    "calendar.selected": "Sélectionné",
    "calendar.legend": "Légende",
    "project.how_it_works.step1_desc": "Décrivez vos besoins en détail",
    "project.how_it_works.step2_title": "Recevez des propositions",
    "project.how_it_works.step2_desc": "Les prestataires vous contactent",
    "project.how_it_works.step3_title": "Choisissez le meilleur",
    "project.how_it_works.step3_desc": "Comparez et sélectionnez",
    "project.recent.title": "Projets Récents",
    "project.status.completed": "Terminé",
    "project.status.active": "Actif",
    "project.proposals": "propositions",
    "project.examples.ac_installation": "Installation climatisation",
    "project.examples.bathroom_renovation": "Rénovation salle de bain", 
    "project.examples.gardening": "Jardinage et entretien",
    "project.tips.title": "Conseils pour réussir",
    "project.tips.tip1": "Soyez précis dans votre description",
    "project.tips.tip2": "Mentionnez votre budget réaliste",
    "project.tips.tip3": "Ajoutez des photos si nécessaire",
    "project.tips.tip4": "Répondez rapidement aux prestataires",
    
    // Cities
    "cities.casablanca": "Casablanca",
    "cities.rabat": "Rabat",
    "cities.marrakech": "Marrakech",
    
    // Header
    "header.register": "Inscription",
    "header.login": "Connexion",
    "header.language": "Langue",
    "header.sos": "SOS",
    "header.sos_alert": "Service SOS activé - Aide d'urgence en cours",
    
    // Messages page
    "messages.badge": "Messages",
    "messages.title": "Mes Conversations",
    "messages.description": "Communiquez directement avec les prestataires",
    "messages.conversations": "Conversations",
    "messages.no_conversations": "Aucune conversation",
    "messages.start_conversation": "Commencez une conversation",
    "messages.last_message_1": "Le devis sera prêt demain",
    "messages.last_message_2": "Parfait, je confirme pour jeudi",
    "messages.last_message_3": "Photos envoyées",
    
    // Profile page
    "profile.stats.projects": "Projets",
    "profile.stats.rating": "Note",
    "profile.stats.favorites": "Favoris",
    "profile.verified": "Vérifié",
    "profile.member_since": "Membre depuis",
    "profile.account_settings": "Paramètres du compte",
    "profile.menu.edit_profile": "Modifier le profil",
    "profile.menu.edit_profile_desc": "Informations personnelles et photo",
    "profile.menu.verification": "Vérification",
    "profile.menu.verification_desc": "Vérifiez votre identité",
    "profile.menu.payments": "Paiements",
    "profile.menu.payments_desc": "Moyens de paiement et facturation",

    "profile.overview": "Aperçu",
    "profile.completed_missions": "Missions terminées",
    "profile.favorite_providers": "Prestataires favoris",
    "profile.average_rating": "Note moyenne reçue",
    "profile.reserved_missions": "Missions réservées",
    "profile.reviews_received": "Avis reçus des prestataires",
    
    // Common
    "common.configure": "Configurer",
    "common.search": "Rechercher",
    
    // SOS
      "sos.title": "Service SOS 24/7",
      "sos.subtitle": "Urgences ? Nous Sommes Là !",
      "sos.description": "Accès direct aux numéros d'urgence officiels avec géolocalisation automatique",
      "sos.police": "Police",
      "sos.fire": "Pompiers/SAMU",
      "sos.gendarmerie": "Gendarmerie",
      "sos.call_now": "Appeler Maintenant",
      "sos.available_24": "Disponible 24h/24",
      "sos.auto_geolocation": "Géolocalisation automatique",
      "sos.direct_call": "Appel direct",
      "sos.emergency_numbers_title": "Numéros d'Urgence Officiels",
      "sos.emergency_numbers_desc": "Contacts directs avec les services de secours marocains",
      "sos.police_desc": "Urgences de sécurité, accidents et situations d'urgence nécessitant une intervention policière",
      "sos.fire_desc": "Urgences médicales, incendies et situations nécessitant une intervention des secours",
      "sos.gendarmerie_desc": "Urgences en zones rurales et situations nécessitant l'intervention de la gendarmerie",
      "sos.available_always": "24h/24, 7j/7",
      "sos.first_aid_title": "Gestes de premiers secours à connaître",
      "sos.first_aid_desc": "Instructions simples et claires pour réagir en cas d'urgence",
      "sos.choking.title": "Étouffement",
      "sos.choking.step1": "Demandez à la personne de tousser fort",
      "sos.choking.step2": "Donnez 5 tapes dans le dos",
      "sos.choking.step3": "Si ça ne marche pas, faites la manœuvre de Heimlich",
      "sos.choking.step4": "Appelez les secours si ça continue",
      "sos.burn.title": "Brûlure",
      "sos.burn.step1": "Refroidissez avec de l'eau (15-20 minutes)",
      "sos.burn.step2": "Ne mettez pas de glace directement",
      "sos.burn.step3": "Couvrez avec un linge propre",
      "sos.burn.step4": "Appelez les secours si c'est grave",
      "sos.unconscious.title": "Perte de connaissance",
      "sos.unconscious.step1": "Vérifiez si la personne respire",
      "sos.unconscious.step2": "Mettez-la en position latérale de sécurité",
      "sos.unconscious.step3": "Appelez immédiatement les secours",
      "sos.unconscious.step4": "Restez avec elle jusqu'à l'arrivée",
      "sos.bleeding.title": "Saignement",
      "sos.bleeding.step1": "Appuyez directement sur la blessure",
      "sos.bleeding.step2": "Utilisez un linge propre",
      "sos.bleeding.step3": "Surélevez le membre si possible",
      "sos.bleeding.step4": "Appelez les secours si c'est important",
      "sos.electrocution.title": "Électrocution",
      "sos.electrocution.step1": "Ne touchez pas la personne directement",
      "sos.electrocution.step2": "Coupez le courant si possible",
      "sos.electrocution.step3": "Utilisez un objet non conducteur",
      "sos.electrocution.step4": "Appelez immédiatement les secours",
      "sos.heatstroke.title": "Coup de chaleur",
      "sos.heatstroke.step1": "Mettez la personne à l'ombre",
      "sos.heatstroke.step2": "Donnez-lui de l'eau à boire",
      "sos.heatstroke.step3": "Refroidissez avec de l'eau",
      "sos.heatstroke.step4": "Appelez les secours si nécessaire",
      "sos.safety_tips_title": "Conseils de Sécurité",
      "sos.safety_tips_desc": "Comment bien utiliser les services d'urgence",
      "sos.before_call.title": "Avant d'Appeler",
      "sos.before_call.tip1": "Gardez votre calme et parlez clairement",
      "sos.before_call.tip2": "Préparez votre adresse exacte",
      "sos.before_call.tip3": "Décrivez précisément la situation",
      "sos.info_to_give.title": "Informations à Donner",
      "sos.info_to_give.tip1": "Votre nom et numéro de téléphone",
      "sos.info_to_give.tip2": "Adresse précise avec points de repère",
      "sos.info_to_give.tip3": "Nature de l'urgence et nombre de personnes impliquées",
      "sos.notice_title": "Avertissement Important",
      "sos.notice_desc": "Les numéros d'urgence sont réservés aux situations d'urgence réelle. L'utilisation abusive de ces services est passible d'amendes et de poursuites.",
    
    // Testimonials
    "testimonials.title": "Ce que disent nos utilisateurs",
    "testimonials.subtitle": "Des milliers de clients satisfaits nous font confiance",
    
    // Newsletter
    "newsletter.title": "Restez informé avec notre newsletter",
    "newsletter.subtitle": "Inscrivez-vous gratuitement et ne manquez aucune actualité de Khadamat",
    "newsletter.placeholder": "Votre email",
    "newsletter.subscribe": "S'inscrire",
    "newsletter.privacy": "Vos données sont protégées et ne seront jamais partagées",
    
    // Footer
    "footer.tagline": "La plateforme qui connecte les clients aux meilleurs prestataires de services du Maroc.",
    "footer.services": "Services",
    "footer.company": "Entreprise",
    "footer.support": "Support",
    "footer.careers": "Carrières",
    "footer.press": "Presse",
    "footer.partners": "Partenaires",
    "footer.help": "Centre d'aide",
    "footer.faq": "FAQ",
    "footer.terms": "Conditions d'utilisation",
    "footer.privacy": "Politique de confidentialité",
    "footer.rights": "Tous droits réservés.",
      "footer.made_in": "Développé avec ❤️ au Maroc",

      // FAQ
      "faq.title": "Foire Aux Questions",
      "faq.subtitle": "Trouvez rapidement les réponses à vos questions",
      "faq.q1": "Comment puis-je trouver un prestataire de confiance ?",
      "faq.a1": "Tous nos prestataires sont vérifiés. Consultez leurs profils, leurs avis clients et leur statut Club Pro pour faire le meilleur choix.",
      "faq.q2": "Que signifie le badge Club Pro ?",
      "faq.a2": "Le badge Club Pro garantit que le prestataire a été vérifié : documents professionnels, assurance, et reconnaissance faciale validés.",
      "faq.q3": "Comment publier un projet ?",
      "faq.a3": "Cliquez sur 'Publier un projet', décrivez vos besoins, votre budget et votre localisation. Les prestataires vous contacteront avec leurs propositions.",
      "faq.q4": "Les paiements sont-ils sécurisés ?",
      "faq.a4": "Oui, tous les paiements sont sécurisés et protégés. Nous utilisons les dernières technologies de chiffrement.",
      "faq.q5": "Comment contacter le support ?",
      "faq.a5": "Vous pouvez nous contacter via la page Contact ou utiliser le chat en ligne disponible 24/7.",
    
    // Featured Providers
    "featured_providers.title": "Prestataires en Vedette",
    "featured_providers.subtitle": "Découvrez nos meilleurs prestataires sélectionnés selon leur note et leur expérience",
    "featured_providers.verified": "Vérifié",
    "featured_providers.pro": "Pro",
    "featured_providers.reviews": "avis",
    "featured_providers.view_profile": "Voir le profil",
    "featured_providers.view_all": "Voir tous les prestataires",
    
    // Common
    "common.currency": "DH",
    "footer.secure": "Paiements Sécurisés",
    
    // Mobile navigation
    "mobile.home": "Accueil",
    "mobile.search": "Recherche",
    "mobile.post": "Publier",
    "mobile.messages": "Messages",
    "mobile.profile": "Profil",
    
    // Common
    "common.join": "Rejoindre Khadamat",
    "common.loading": "Chargement...",
    "common.error": "Une erreur s'est produite",
    "common.retry": "Réessayer",
    
    // Statistics
    "stats.providers": "Prestataires",
    "stats.missions": "Missions",
    "stats.satisfaction": "Satisfaction",
    "stats.support": "Support",
    
    // Testimonials
    "testimonials.review1": "Excellent service ! Le prestataire était ponctuel, professionnel et le travail était parfait. Je recommande vivement.",
    "testimonials.review2": "Très satisfait de la qualité du service. Prix raisonnable et délais respectés. Je ferai appel à nouveau.",
    "testimonials.review3": "Plateforme très pratique pour trouver des prestataires fiables. L'interface est intuitive et le service client réactif.",
    "testimonials.user1": "Fatima Z.",
    "testimonials.user2": "Ahmed M.",
    "testimonials.user3": "Khadija L.",
    "testimonials.city1": "Casablanca",
    "testimonials.city2": "Rabat",
    "testimonials.city3": "Marrakech",
    
    // Newsletter
    "newsletter.stay_informed": "Restez informé des nouveautés et des offres dans votre région",
    "newsletter.description": "Inscrivez-vous gratuitement et ne manquez aucune actualité de Khadamat. Recevez des offres personnalisées pour",
    "newsletter.email_placeholder": "Entrez votre adresse email",
    "newsletter.subscribing": "Inscription...",
    "newsletter.subscribe_button": "S'inscrire",
    "newsletter.success_message": "✅ Inscription réussie ! Vous recevrez bientôt nos actualités personnalisées pour",
    "newsletter.what_you_get": "Ce que vous recevrez :",
    "newsletter.site_news_title": "Actualités du site",
    "newsletter.site_news_desc": "Nouvelles fonctionnalités et améliorations de la plateforme",
    "newsletter.local_offers_title": "Offres localisées",
    "newsletter.local_offers_desc": "Promotions et prestataires disponibles dans votre région",
    "newsletter.useful_tips_title": "Conseils utiles",
    "newsletter.useful_tips_desc": "Astuces et guides pratiques pour vos projets",
    "newsletter.security_title": "Sécurité garantie",
    "newsletter.security_desc": "Vos données sont protégées et ne seront jamais partagées",
    "newsletter.no_spam": "Pas de spam, désabonnement en un clic",
    "newsletter.your_region": "votre région",
    
    // Join Providers
    "join_providers.title": "Rejoignez notre communauté de professionnels certifiés",
    "join_providers.subtitle": "Développez votre activité, gagnez la confiance des clients et accédez à de nouveaux projets avec notre plateforme de confiance.",
    "join_providers.become_provider": "Devenir prestataire",
    "join_providers.club_pro": "Club Pro",
    "join_providers.develop_activity_title": "Développez votre activité",
    "join_providers.develop_activity_desc": "Accédez à de nouveaux clients et projets réguliers",
    "join_providers.gain_trust_title": "Gagnez la confiance",
    "join_providers.gain_trust_desc": "Badge de vérification et avis clients pour vous démarquer",
    "join_providers.competitive_prices_title": "Tarifs compétitifs",
    "join_providers.competitive_prices_desc": "Fixez vos prix et maximisez vos revenus",
    
    // Booking Modal
    "booking.title": "Réserver",
    "booking.description_label": "Description de votre demande",
    "booking.description_placeholder": "Décrivez en détail ce que vous souhaitez faire (ex: réparation de robinet, installation électrique, nettoyage complet...)",
    "booking.confirm": "Confirmer la réservation",
    
    // Common
    "common.cancel": "Annuler",
    "common.language": "fr",
    
    // Prestataires page
    "prestataires.title": "Trouvez un Prestataire près de chez vous",
    "prestataires.subtitle": "Découvrez nos prestataires vérifiés et qualifiés pour tous vos besoins",
    "prestataires.search_placeholder": "Rechercher un prestataire...",
    "prestataires.filters": "Filtres",
    "prestataires.service_label": "Service",
    "prestataires.all_services": "Tous les services",
    "prestataires.city_label": "Ville",
    "prestataires.all_cities": "Toutes les villes",
    "prestataires.rating_label": "Note minimum",
    "prestataires.all_ratings": "Toutes les notes",
    "prestataires.stars": "étoiles",
    "prestataires.clear_filters": "Effacer les filtres",
    "prestataires.results_count": "prestataire trouvé",
    "prestataires.results_count_plural": "prestataires trouvés",
    "prestataires.no_results_title": "Aucun prestataire trouvé",
    "prestataires.no_results_desc": "Essayez de modifier vos critères de recherche ou de supprimer certains filtres.",
    "prestataires.clear_all_filters": "Effacer tous les filtres",
    
    // Provider Profile
    "provider_profile.book_provider": "Réserver ce prestataire",
    "provider_profile.contact_description": "Contactez le prestataire pour discuter de votre projet",
    "provider_profile.book_now": "Réserver maintenant",
    "provider_profile.message": "Message",
    "provider_profile.call": "Appeler",
    "provider_profile.mission_description": "Description de la mission",
    "provider_profile.mission_placeholder": "Décrivez votre projet...",
    "provider_profile.cancel": "Annuler",
    "provider_profile.confirm": "Confirmer",

    // Reservations page
    "reservations.manage": "Gérez vos réservations et suivez l'état de vos services",
    "reservations.filters.all": "Toutes",
    "reservations.filters.pending": "En attente",
    "reservations.filters.confirmed": "Confirmées",
    "reservations.filters.completed": "Terminées",
    "reservations.status.confirmed": "confirmée",
    "reservations.status.pending": "en attente",
    "reservations.status.completed": "terminée",
    "reservations.contact": "Contacter",
    "reservations.details": "Voir détails",
    "reservations.empty.title": "Aucune réservation",
    "reservations.empty.desc": "Vous n'avez pas encore de réservations. Commencez par rechercher un service !",
    "reservations.empty.cta": "Rechercher un service",

    // Favorites page
    "favorites.description": "Vos prestataires préférés et les services que vous aimez",
    "favorites.stats.total": "Total favoris",
    "favorites.stats.online": "En ligne",
    "favorites.stats.club_pro": "Club Pro",
    "favorites.message": "Message",
    "favorites.call": "Appeler",
    "favorites.empty.title": "Aucun favori",
    "favorites.empty.desc": "Vous n'avez pas encore ajouté de prestataires à vos favoris. Commencez par explorer nos services !",
    "favorites.empty.cta": "Découvrir des prestataires",

    // Messages page
    "messages.search_placeholder": "Rechercher...",
    "messages.just_now": "À l'instant",

    // Settings page
    "settings.title": "Réglages",
    "settings.description": "Gérez vos préférences et paramètres de compte",
    "settings.profile_section": "Profil et informations",
    "settings.profile.personal": "Informations personnelles",
    "settings.profile.avatar": "Avatar et photo",
    "settings.profile.language": "Préférences de langue",
    "settings.security_section": "Sécurité et accès",
    "settings.security.password": "Mot de passe",
    "settings.security.2fa": "Authentification à deux facteurs",
    "settings.security.sessions": "Sessions actives",
    "settings.notifications_section": "Notifications",
    "settings.notifications.manage": "Paramètres de notifications",
    "settings.notifications.email": "Email",
    "settings.notifications.sms": "SMS",
    "settings.notifications.push": "Notifications push",
    "settings.theme.dark_mode": "Mode sombre",
    "settings.actions.logout": "Se déconnecter",
    "settings.actions.delete_account": "Supprimer le compte",
    "settings.actions.export_data": "Exporter les données",
  },
  ar: {
    // Navigation
    "nav.home": "الرئيسية",
    "nav.services": "الخدمات",
    "nav.providers": "مقدمو الخدمات",
    "nav.club_pro": "نادي المحترفين",
    "nav.project": "المشاريع",
    "nav.support": "الدعم",
    "nav.login": "تسجيل الدخول",
    "nav.register": "التسجيل",
    "nav.messages": "الرسائل",
    "nav.contact": "اتصل بنا",
    "nav.about": "حول",
    "nav.profile": "الملف الشخصي",
    
    // User Profile Menu
    "profile.menu.profile": "الملف الشخصي",
    "profile.menu.orders": "طلباتي",
    "profile.menu.reservations": "حجوزاتي",
    "profile.menu.favorites": "المفضلة",
    "profile.menu.missions": "مهامي",
    "profile.menu.club_pro": "النادي المميز",
    "profile.menu.messages": "الرسائل",
    "profile.menu.settings": "الإعدادات",
    "profile.menu.logout": "تسجيل الخروج",
    "profile.role.client": "عميل",
    "profile.role.provider": "مقدم خدمة",
    
    // Hero section
    "hero.title": "ابحث عن",
    "hero.title_highlight": "مقدم الخدمة المناسب",
    "hero.subtitle": "أول منصة مغربية تربط العملاء بمقدمي الخدمات المهنية",
    "hero.search_placeholder": "ماذا تبحث عن؟ (مثل: سباك، كهربائي...)",
    "hero.search_button": "بحث",
    "hero.location": "الدار البيضاء",
    "hero.city_placeholder": "المدينة (مثل: الدار البيضاء، الرباط...)",
    "hero.provider_placeholder": "البحث عن مقدم خدمة محدد (اختياري)",
    
    // Services
    "services.title": "خدماتنا الشائعة",
    "services.subtitle": "اكتشف مجموعتنا الواسعة من الخدمات المهنية المتاحة في جميع أنحاء المغرب",
    "services.explore": "استكشف جميع الخدمات",
    "services.popular": "الخدمات الشائعة",
    "services.popular_in": "الخدمات الشائعة في",
    "services.plumbing": "السباكة",
    "services.electricity": "الكهرباء",
    "services.cleaning": "التنظيف",
    "services.gardening": "البستنة",
    "services.painting": "الدهان",
    "services.repair": "الإصلاح",
    "services.installation": "التركيب",
    "services.deep_cleaning": "التنظيف العميق",
    "services.moving": "النقل",
    "services.providers_count": {
      one: "{{count}} مقدم خدمة",
      two: "{{count}} مقدمي خدمة",
      few: "{{count}} مقدمي خدمة",
      many: "{{count}} مقدم خدمة",
      other: "{{count}} مقدمي خدمة"
    },
    
    // How it works
    "how_it_works.title": "كيف يعمل؟",
    "how_it_works.subtitle": "اعثر على مقدم الخدمة المناسب في 3 خطوات بسيطة",
    "how_it_works.step1": "1. ابحث",
    "how_it_works.step1_desc": "صف ما تحتاجه. اذكر موقعك. وسنقوم بالباقي.",
    "how_it_works.step2": "2. قارن",
    "how_it_works.step2_desc": "قارن الملفات. اقرأ الآراء. اختر الأنسب.",
    "how_it_works.step3": "3. تواصل",
    "how_it_works.step3_desc": "تواصل مباشرة. اتفق على التفاصيل. احجز خدمتك.",
    
    // Testimonials
    "testimonials.title": "ماذا يقول عملاؤنا",
    "testimonials.subtitle": "آلاف العملاء الراضين يثقون بنا",
    
    // Providers
    "providers.title": "مقدمو خدمات معتمدون",
    "providers.subtitle": "اكتشف مقدمي خدمات نادي المحترفين المعتمدين وذوي المؤهلات العالية",
    "providers.club_pro_badge": "نادي المحترفين معتمد",
    "providers.online": "متصل",
    "providers.contact": "اتصل",
    "providers.reviews": "مراجعة",
    "providers.view_profile": "الملف الشخصي",
    
    // Chat
    "chat.title": "المراسلة الفورية",
    "chat.subtitle": "تواصل مباشرة مع مقدمي الخدمات من خلال نظام المراسلة الفورية مع المكالمات الصوتية والمرئية المدمجة.",
    "chat.features.realtime": "رسائل في الوقت الفعلي",
    "chat.features.calls": "مكالمات صوتية ومرئية",
    "chat.features.files": "مشاركة ملفات آمنة",
    "chat.input_placeholder": "اكتب رسالتك...",
    
    // Club Pro
    "club_pro.title": "انضم إلى نخبة مقدمي الخدمات",
    "club_pro.subtitle": "احصل على ميزات مميزة وزد من ظهورك مع برنامج نادي المحترفين المعتمد",
    "club_pro.home_subtitle": "احصل على المشاريع الكبيرة واستفد من المزايا الحصرية مقابل 50 درهم فقط شهرياً.",
    "club_pro.cta": "أصبح محترف نادي",
    "club_pro.join_cta": "انضم لنادي المحترفين - 50 درهم/شهر",
    "club_pro.badge_benefit": "شارة نادي المحترفين للتميز",
    "club_pro.priority_benefit": "الأولوية في نتائج البحث",
    "club_pro.support_benefit": "دعم مخصص لمقدمي خدمات نادي المحترفين",
    "club_pro.exclusive_access": "🏆 وصول حصري",
    "club_pro.large_projects": "المشاريع الكبيرة حصرية لنادي المحترفين",
    "club_pro.verification.title": "التحقق الكامل",
    "club_pro.verification.desc": "المستندات المهنية المعتمدة: البراءة، السجل التجاري، التأمين والتعرف على الوجه",
    "club_pro.visibility.title": "ظهور مميز",
    "club_pro.visibility.desc": "ظهر في أعلى نتائج البحث مع شارة نادي المحترفين المميزة",
    "club_pro.trust.title": "ثقة معززة",
    "club_pro.trust.desc": "اكسب ثقة العملاء مع حالتك المعتمدة والضمانات الممتدة",
    "club_pro.verification_24h": "التحقق خلال 24 ساعة",
    "club_pro.priority_support": "دعم أولوي",
    "club_pro.premium_badge": "شارة مميزة",
    "club_pro.why_choose": "لماذا تختار نادي المحترفين؟",
    "club_pro.join_elite": "انضم إلى نخبة مقدمي الخدمات وضاعف فرصك",
    "club_pro.benefit_badge_title": "شارة نادي المحترفين المميزة",
    "club_pro.benefit_badge_desc": "سيتم وضع علامة على ملفك الشخصي بشارة مميزة مرئية لجميع العملاء",
    "club_pro.benefit_ranking_title": "ترتيب أولوي",
    "club_pro.benefit_ranking_desc": "تظهر أولاً في نتائج البحث",
    "club_pro.benefit_projects_title": "الوصول إلى المشاريع المميزة",
    "club_pro.benefit_projects_desc": "احصل على طلبات المشاريع الأكثر قيمة",
    "club_pro.benefit_support_title": "دعم العملاء الأولوي",
    "club_pro.benefit_support_desc": "مساعدة مخصصة ووقت استجابة متسارع",
    "club_pro.pricing_title": "اشتراك واحد، جميع المزايا",
    "club_pro.pricing_subtitle": "انضم إلى نادي المحترفين واحصل على أكبر المشاريع",
    "club_pro.per_month": "شهرياً",
    "club_pro.commitment_1_year": "التزام لسنة واحدة",
    "club_pro.join_button": "انضم إلى نادي المحترفين",
      "club_pro.payment_methods": "وسائل الدفع المقبولة",
      "club_pro.benefits_title": "مزاياك الحصرية",
      "club_pro.benefits_subtitle": "اكتشف جميع المزايا المخصصة لأعضاء كلوب برو",
      "club_pro.benefits.badge.title": "شارة موثقة",
      "club_pro.benefits.badge.desc": "ملف موثق مع شارة برتقالية",
      "club_pro.benefits.badge.highlight": "حصري",
      "club_pro.benefits.ranking.title": "ترتيب أولوية",
      "club_pro.benefits.ranking.desc": "الأول في نتائج البحث",
      "club_pro.benefits.ranking.highlight": "مميز",
      "club_pro.benefits.clients.title": "عملاء مميزون",
      "club_pro.benefits.clients.desc": "وصول إلى أكثر العملاء قيمة",
      "club_pro.benefits.clients.highlight": "حصري",
      "club_pro.benefits.support.title": "دعم مخصص",
      "club_pro.benefits.support.desc": "استجابة مضمونة في أقل من ساعة",
      "club_pro.benefits.support.highlight": "24/7",
      "club_pro.benefits.reservations.title": "حجوزات متقدمة",
      "club_pro.benefits.reservations.desc": "تخطيط وإدارة محسّنة",
      "club_pro.benefits.reservations.highlight": "ذكي",
      "club_pro.benefits.pricing.title": "أسعار مميزة",
      "club_pro.benefits.pricing.desc": "أسعار أعلى لخدماتك",
      "club_pro.benefits.pricing.highlight": "+40%",
      "club_pro.stats.more_clients": "عملاء أكثر",
      "club_pro.stats.revenue_increase": "زيادة في رقم المعاملات",
      "club_pro.stats.priority_support": "دعم ذو أولوية",
      "club_pro.stats.satisfaction": "رضا",
      "club_pro.simple_pricing_title": "تسعير بسيط",
      "club_pro.simple_pricing_desc": "خطة واحدة تشمل جميع المزايا",
      "club_pro.commitment_secure": "التزام لمدة سنة - دفع آمن",
      "club_pro.join_now": "انضم الآن",
      "club_pro.secure_payment": "دفع آمن - بطاقة بنكية، باي بال، أورانج موني",
      "club_pro.testimonials_title": "حوّلوا نشاطهم",
      "club_pro.testimonials_subtitle": "اكتشف شهادات مقدمي خدمات كلوب برو",
      "club_pro.testimonials.ahmed.role": "كهربائي كلوب برو",
      "club_pro.testimonials.ahmed.text": "منذ انضمامي إلى كلوب برو حصلت على عدد عملاء أكثر بثلاث مرات. الشارة الموثقة أحدثت الفرق!",
      "club_pro.testimonials.ahmed.highlight": "+300% عملاء",
      "club_pro.testimonials.fatima.role": "تنظيف كلوب برو",
      "club_pro.testimonials.fatima.text": "الدعم المخصص استثنائي. أحصل على رد في أقل من ساعة في كل مرة!",
      "club_pro.testimonials.fatima.highlight": "دعم 24/7",
      "club_pro.testimonials.mohammed.role": "سباك كلوب برو",
      "club_pro.testimonials.mohammed.text": "الظهور أولاً في نتائج البحث ضاعف نشاطي بنسبة 200%!",
      "club_pro.testimonials.mohammed.highlight": "+200% رقم معاملات",
      "club_pro.cta_title": "هل أنت مستعد للانضمام إلى النخبة؟",
      "club_pro.cta_subtitle": "انضم إلى كلوب برو وحوّل نشاطك اليوم",
      "club_pro.cta_join": "انضم إلى كلوب برو",
      "club_pro.cta_learn_more": "اعرف المزيد",
      "club_pro.cta_features": "✓ تحقق خلال 24 ساعة • ✓ دعم أولوية • ✓ بدون التزام",
    
    // Project page
    "project.hero.badge": "نشر مشروع",
    "project.hero.find_the": "اعثر على",
    "project.hero.ideal_provider": "مقدم الخدمة المثالي",
    "project.hero.description": "صف مشروعك واحصل على عروض من مقدمي خدمات مؤهلين. قارن العروض واختر أفضل محترف لاحتياجاتك.",
    "project.form.title": "نشر مشروع جديد",
    
    // Search and filters
    "search.suggestions": "اقتراحات",
    "search.clear_filters": "مسح المرشحات",
    "search.active_filters": "المرشحات النشطة",
    "search.search_term": "بحث",
    "search.service": "خدمة",
    "search.city": "مدينة",
    "search.price": "سعر",
    "search.available": "متاح",
    "search.club_pro": "نادي المحترفين",
    "search.date": "تاريخ",
    "calendar.available": "متاح",
    "calendar.unavailable": "غير متاح",
    "calendar.selected": "محدد",
    "calendar.legend": "مفتاح",
    "project.form.project_title": "عنوان المشروع",
    "project.form.title_placeholder": "مثال: تركيب كهرباء في الصالون",
    "project.form.category": "الفئة",
    "project.form.category_placeholder": "اختر فئة",
    "project.form.budget": "الميزانية",
    "project.form.budget_placeholder": "حدد الميزانية",
    "project.form.location": "الموقع",
    "project.form.location_placeholder": "مثال: الدار البيضاء، المعاريف",
    "project.form.deadline": "الموعد المطلوب",
    "project.form.deadline_placeholder": "مثال: خلال الأسبوع، عاجل",
    "project.form.description": "وصف مفصل",
    "project.form.description_placeholder": "صف مشروعك بالتفصيل: الأعمال المطلوبة، القيود، المواد المقدمة أم لا...",
    "project.form.skills": "المهارات المطلوبة",
    "project.form.skills_placeholder": "مثال: كهربائي معتمد، خبرة في المنازل الذكية",
    "project.form.publishing": "جاري النشر...",
    "project.form.publish_button": "نشر المشروع",
    "project.form.other": "أخرى",
    "project.budget.under_500": "أقل من 500 درهم",
    "project.budget.500_1000": "500 - 1000 درهم",
    "project.budget.1000_2000": "1000 - 2000 درهم",
    "project.budget.2000_5000": "2000 - 5000 درهم",
    "project.budget.over_5000": "أكثر من 5000 درهم",
    "project.budget.negotiable": "قابل للتفاوض",
    "project.toast.success_title": "تم نشر المشروع!",
    "project.toast.success_description": "تم نشر مشروعك بنجاح. سيتلقى مقدمو الخدمات إشعارات.",
    "project.toast.error_title": "خطأ في النشر",
    "project.toast.error_description": "حدث خطأ أثناء النشر.",
    "project.how_it_works.title": "كيف يعمل؟",
    "project.how_it_works.step1_title": "انشر مشروعك",
    "project.how_it_works.step1_desc": "صف احتياجاتك بالتفصيل",
    "project.how_it_works.step2_title": "احصل على عروض",
    "project.how_it_works.step2_desc": "مقدمو الخدمات سيتواصلون معك",
    "project.how_it_works.step3_title": "اختر الأفضل",
    "project.how_it_works.step3_desc": "قارن واختر",
    "project.recent.title": "المشاريع الحديثة",
    "project.status.completed": "مكتمل",
    "project.status.active": "نشط",
    "project.proposals": "عروض",
    "project.examples.ac_installation": "تركيب تكييف",
    "project.examples.bathroom_renovation": "تجديد الحمام",
    "project.examples.gardening": "البستنة والصيانة",
    "project.tips.title": "نصائح للنجاح",
    "project.tips.tip1": "كن دقيقاً في وصفك",
    "project.tips.tip2": "اذكر ميزانيتك الواقعية",
    "project.tips.tip3": "أضف صوراً إذا لزم الأمر",
    "project.tips.tip4": "رد بسرعة على مقدمي الخدمات",
    
    // Cities
    "cities.casablanca": "الدار البيضاء",
    "cities.rabat": "الرباط",
    "cities.marrakech": "مراكش",
    
    // Header
    "header.register": "التسجيل",
    "header.login": "تسجيل الدخول",
    "header.language": "اللغة",
    "header.sos": "طوارئ",
    "header.sos_alert": "تم تفعيل خدمة الطوارئ - المساعدة العاجلة قيد التقدم",
    
    // Messages page
    "messages.badge": "الرسائل",
    "messages.title": "محادثاتي",
    "messages.description": "تواصل مباشرة مع مقدمي الخدمات",
    "messages.conversations": "المحادثات",
    "messages.no_conversations": "لا توجد محادثات",
    "messages.start_conversation": "ابدأ محادثة",
    "messages.last_message_1": "العرض سيكون جاهزاً غداً",
    "messages.last_message_2": "ممتاز، أؤكد ليوم الخميس",
    "messages.last_message_3": "تم إرسال الصور",
    
    // Profile page
    "profile.stats.projects": "المشاريع",
    "profile.stats.rating": "التقييم",
    "profile.stats.favorites": "المفضلة",
    "profile.verified": "موثق",
    "profile.member_since": "عضو منذ",
    "profile.account_settings": "إعدادات الحساب",
    "profile.menu.edit_profile": "تعديل الملف الشخصي",
    "profile.menu.edit_profile_desc": "المعلومات الشخصية والصورة",
    "profile.menu.verification": "التوثيق",
    "profile.menu.verification_desc": "تحقق من هويتك",
    "profile.menu.payments": "المدفوعات",
    "profile.menu.payments_desc": "وسائل الدفع والفواتير",

    "profile.overview": "نظرة عامة",
    "profile.completed_missions": "المهام المنجزة",
    "profile.favorite_providers": "المقدّمون المفضلون",
    "profile.average_rating": "متوسط التقييم",
    "profile.reserved_missions": "المهام المحجوزة",
    "profile.reviews_received": "التقييمات المستلمة من مقدمي الخدمات",

    // Common
    "common.configure": "تكوين",
    "common.search": "بحث",
    
    // SOS
    "sos.title": "خدمة الطوارئ 24/7",
    "sos.subtitle": "طوارئ؟ نحن هنا!",
    "sos.description": "الوصول المباشر لأرقام الطوارئ الرسمية مع تحديد الموقع الجغرافي التلقائي",
      "sos.police": "الشرطة",
      "sos.fire": "الإطفاء/الإسعاف",
      "sos.gendarmerie": "الدرك الملكي",
      "sos.call_now": "اتصل الآن",
      "sos.available_24": "متاح 24 ساعة/24",
      "sos.auto_geolocation": "تحديد الموقع التلقائي",
      "sos.direct_call": "اتصال مباشر",
      "sos.emergency_numbers_title": "أرقام الطوارئ الرسمية",
      "sos.emergency_numbers_desc": "اتصالات مباشرة مع خدمات الإنقاذ المغربية",
      "sos.police_desc": "حالات الطوارئ الأمنية والحوادث التي تتطلب تدخل الشرطة",
      "sos.fire_desc": "حالات الطوارئ الطبية والحرائق التي تتطلب تدخل فرق الإنقاذ",
      "sos.gendarmerie_desc": "طوارئ في المناطق القروية وحالات تتطلب تدخل الدرك الملكي",
      "sos.available_always": "24 ساعة/24، 7 أيام/7",
      "sos.first_aid_title": "حركات الإسعافات الأولية التي يجب معرفتها",
      "sos.first_aid_desc": "تعليمات بسيطة وواضحة للتصرف في حالة الطوارئ",
      "sos.choking.title": "اختناق",
      "sos.choking.step1": "اطلب من الشخص أن يسعل بقوة",
      "sos.choking.step2": "أعطِ 5 ضربات على الظهر",
      "sos.choking.step3": "إذا لم ينجح، قم بمناورة هيمليك",
      "sos.choking.step4": "اتصل بالإسعاف إذا استمر الأمر",
      "sos.burn.title": "حرق",
      "sos.burn.step1": "برّد بالماء لمدة 15-20 دقيقة",
      "sos.burn.step2": "لا تضع الثلج مباشرة",
      "sos.burn.step3": "غطِّ بقطعة قماش نظيفة",
      "sos.burn.step4": "اتصل بالإسعاف إذا كان خطيرًا",
      "sos.unconscious.title": "فقدان الوعي",
      "sos.unconscious.step1": "تحقق إذا كان الشخص يتنفس",
      "sos.unconscious.step2": "ضعه في وضعية الاستلقاء الجانبي",
      "sos.unconscious.step3": "اتصل بالإسعاف فورًا",
      "sos.unconscious.step4": "ابقَ معه حتى وصول المساعدة",
      "sos.bleeding.title": "نزيف",
      "sos.bleeding.step1": "اضغط مباشرة على الجرح",
      "sos.bleeding.step2": "استعمل قطعة قماش نظيفة",
      "sos.bleeding.step3": "ارفع العضو إن أمكن",
      "sos.bleeding.step4": "اتصل بالإسعاف إذا كان كبيرًا",
      "sos.electrocution.title": "صعق كهربائي",
      "sos.electrocution.step1": "لا تلمس الشخص مباشرة",
      "sos.electrocution.step2": "اقطع التيار إن أمكن",
      "sos.electrocution.step3": "استعمل شيئًا غير موصل للكهرباء",
      "sos.electrocution.step4": "اتصل بالإسعاف فورًا",
      "sos.heatstroke.title": "ضربة شمس",
      "sos.heatstroke.step1": "ضع الشخص في الظل",
      "sos.heatstroke.step2": "أعطه ماءً للشرب",
      "sos.heatstroke.step3": "برّد بالماء",
      "sos.heatstroke.step4": "اتصل بالإسعاف إذا لزم الأمر",
      "sos.safety_tips_title": "نصائح السلامة",
      "sos.safety_tips_desc": "كيفية استخدام خدمات الطوارئ بشكل جيد",
      "sos.before_call.title": "قبل الاتصال",
      "sos.before_call.tip1": "ابقَ هادئًا وتحدث بوضوح",
      "sos.before_call.tip2": "حضّر عنوانك الكامل",
      "sos.before_call.tip3": "صف الوضع بدقة",
      "sos.info_to_give.title": "معلومات يجب تقديمها",
      "sos.info_to_give.tip1": "اسمك ورقم هاتفك",
      "sos.info_to_give.tip2": "عنوان دقيق مع معالم",
      "sos.info_to_give.tip3": "طبيعة الطوارئ وعدد الأشخاص المعنيين",
      "sos.notice_title": "تحذير مهم",
      "sos.notice_desc": "أرقام الطوارئ مخصصة للحالات الحقيقية فقط. الاستخدام السيئ لهذه الخدمات يعرضك للغرامات والمتابعات القضائية.",
    
    // Newsletter
    "newsletter.title": "ابق على اطلاع مع نشرتنا الإخبارية",
    "newsletter.subtitle": "اشترك مجاناً ولا تفوت أي أخبار من خدمات",
    "newsletter.placeholder": "بريدك الإلكتروني",
    "newsletter.subscribe": "اشترك",
    "newsletter.privacy": "بياناتك محمية ولن يتم مشاركتها أبداً",
    
    // Footer
    "footer.tagline": "المنصة التي تربط العملاء بأفضل مقدمي الخدمات في المغرب.",
    "footer.services": "الخدمات",
    "footer.company": "الشركة",
    "footer.support": "الدعم",
    "footer.careers": "الوظائف",
    "footer.press": "الصحافة",
    "footer.partners": "الشركاء",
    "footer.help": "مركز المساعدة",
    "footer.faq": "الأسئلة الشائعة",
    "footer.terms": "شروط الاستخدام",
    "footer.privacy": "سياسة الخصوصية",
    "footer.rights": "جميع الحقوق محفوظة.",
      "footer.made_in": "مطور بـ ❤️ في المغرب",
      "footer.secure": "مدفوعات آمنة",

      // FAQ
      "faq.title": "الأسئلة الشائعة",
      "faq.subtitle": "اعثر بسرعة على إجابات أسئلتك",
      "faq.q1": "كيف أجد مقدم خدمة موثوق؟",
      "faq.a1": "جميع مقدمي خدماتنا موثقون. اطلع على ملفاتهم وتقييمات العملاء وشارة نادي المحترفين لاتخاذ أفضل اختيار.",
      "faq.q2": "ماذا تعني شارة نادي المحترفين؟",
      "faq.a2": "شارة نادي المحترفين تعني أن مقدم الخدمة تم التحقق منه: وثائق مهنية، تأمين، وتحقق من الوجه.",
      "faq.q3": "كيف أنشر مشروعًا؟",
      "faq.a3": "انقر على \"نشر مشروع\"، وصف احتياجاتك، ميزانيتك وموقعك. سيتواصل معك مقدمو الخدمات بعروضهم.",
      "faq.q4": "هل المدفوعات آمنة؟",
      "faq.a4": "نعم، جميع المدفوعات آمنة ومحمية. نستخدم أحدث تقنيات التشفير.",
      "faq.q5": "كيف أتواصل مع الدعم؟",
      "faq.a5": "يمكنك التواصل معنا عبر صفحة الاتصال أو استخدام الدردشة المتاحة على مدار الساعة.",
    
    // Featured Providers
    "featured_providers.title": "مقدمو الخدمات المميزون",
    "featured_providers.subtitle": "اكتشف أفضل مقدمي الخدمات المختارين حسب تقييمهم وخبرتهم",
    "featured_providers.verified": "موثق",
    "featured_providers.pro": "محترف",
    "featured_providers.reviews": "مراجعة",
    "featured_providers.view_profile": "عرض الملف الشخصي",
    "featured_providers.view_all": "عرض جميع مقدمي الخدمات",
    
    // Common
    "common.currency": "درهم",
    
    // Mobile navigation
    "mobile.home": "الرئيسية",
    "mobile.search": "بحث",
    "mobile.post": "نشر",
    "mobile.messages": "الرسائل",
    "mobile.profile": "الملف الشخصي",
    
    // Common
    "common.join": "انضم إلى خدمات",
    "common.loading": "جاري التحميل...",
    "common.error": "حدث خطأ",
    "common.retry": "أعد المحاولة",
    
    // Statistics
    "stats.providers": "مقدمو الخدمات",
    "stats.missions": "المهام",
    "stats.satisfaction": "الرضا",
    "stats.support": "الدعم",
    
    // Testimonials
    "testimonials.review1": "خدمة ممتازة! كان مقدم الخدمة دقيقاً ومهنياً والعمل كان مثالياً. أوصي بشدة.",
    "testimonials.review2": "راضٍ جداً من جودة الخدمة. السعر معقول والمواعيد محترمة. سألجأ مرة أخرى.",
    "testimonials.review3": "منصة مفيدة جداً للعثور على مقدمي خدمات موثوقين. الواجهة بديهية وخدمة العملاء متجاوبة.",
    "testimonials.user1": "فاطمة ز.",
    "testimonials.user2": "أحمد م.",
    "testimonials.user3": "خديجة ل.",
    "testimonials.city1": "الدار البيضاء",
    "testimonials.city2": "الرباط",
    "testimonials.city3": "مراكش",
    
    // Newsletter
    "newsletter.stay_informed": "ابق على اطلاع بالأخبار والعروض في منطقتك",
    "newsletter.description": "اشترك مجاناً ولا تفوت أي أخبار من خدمات. احصل على عروض مخصصة لـ",
    "newsletter.email_placeholder": "أدخل بريدك الإلكتروني",
    "newsletter.subscribing": "جاري التسجيل...",
    "newsletter.subscribe_button": "اشترك",
    "newsletter.success_message": "✅ تم التسجيل بنجاح! ستصلك قريباً أخبارنا المخصصة لـ",
    "newsletter.what_you_get": "ما ستحصل عليه:",
    "newsletter.site_news_title": "أخبار الموقع",
    "newsletter.site_news_desc": "ميزات جديدة وتحسينات للمنصة",
    "newsletter.local_offers_title": "عروض محلية",
    "newsletter.local_offers_desc": "عروض ومقدمي خدمات متاحون في منطقتك",
    "newsletter.useful_tips_title": "نصائح مفيدة",
    "newsletter.useful_tips_desc": "حيل وأدلة عملية لمشاريعك",
    "newsletter.security_title": "أمان مضمون",
    "newsletter.security_desc": "بياناتك محمية ولن يتم مشاركتها أبداً",
    "newsletter.no_spam": "لا بريد مزعج، إلغاء الاشتراك بنقرة واحدة",
    "newsletter.your_region": "منطقتك",
    
    // Join Providers
    "join_providers.title": "انضم إلى مجتمعنا من المحترفين المعتمدين",
    "join_providers.subtitle": "طور نشاطك، اكسب ثقة العملاء واحصل على مشاريع جديدة مع منصتنا الموثوقة.",
    "join_providers.become_provider": "أصبح مقدم خدمة",
    "join_providers.club_pro": "نادي المحترفين",
    "join_providers.develop_activity_title": "طور نشاطك",
    "join_providers.develop_activity_desc": "احصل على عملاء ومشاريع جديدة منتظمة",
    "join_providers.gain_trust_title": "اكسب الثقة",
    "join_providers.gain_trust_desc": "شارة التحقق ومراجعات العملاء للتميز",
    "join_providers.competitive_prices_title": "أسعار تنافسية",
    "join_providers.competitive_prices_desc": "حدد أسعارك واعظم أرباحك",
    
    // Booking Modal
    "booking.title": "حجز",
    "booking.description_label": "وصف طلبك",
    "booking.description_placeholder": "صف بالتفصيل ما تريد القيام به (مثل: إصلاح الصنبور، تركيب كهربائي، تنظيف شامل...)",
    "booking.confirm": "تأكيد الحجز",
    
    // Common
    "common.cancel": "إلغاء",
    "common.language": "ar",
    
    // Prestataires page
    "prestataires.title": "اعثر على مقدم خدمة قريب منك",
    "prestataires.subtitle": "اكتشف مقدمي الخدمات المعتمدين والمؤهلين لجميع احتياجاتك",
    "prestataires.search_placeholder": "البحث عن مقدم خدمة...",
    "prestataires.filters": "المرشحات",
    "prestataires.service_label": "الخدمة",
    "prestataires.all_services": "جميع الخدمات",
    "prestataires.city_label": "المدينة",
    "prestataires.all_cities": "جميع المدن",
    "prestataires.rating_label": "الحد الأدنى للتقييم",
    "prestataires.all_ratings": "كل التقييمات",
    "prestataires.stars": "نجوم",
    "prestataires.clear_filters": "مسح المرشحات",
    "prestataires.results_count": "مقدم خدمة وجد",
    "prestataires.results_count_plural": "مقدمو خدمات وجدوا",
    "prestataires.no_results_title": "لم يتم العثور على مقدم خدمة",
    "prestataires.no_results_desc": "حاول تعديل معايير البحث أو إزالة بعض المرشحات.",
    "prestataires.clear_all_filters": "مسح جميع المرشحات",
    
    // Provider Profile
    "provider_profile.book_provider": "حجز هذا مقدم الخدمة",
    "provider_profile.contact_description": "تواصل مع مقدم الخدمة لمناقشة مشروعك",
    "provider_profile.book_now": "احجز الآن",
    "provider_profile.message": "رسالة",
    "provider_profile.call": "اتصال",
    "provider_profile.mission_description": "وصف المهمة",
    "provider_profile.mission_placeholder": "صف مشروعك...",
    "provider_profile.cancel": "إلغاء",
    "provider_profile.confirm": "تأكيد",

    // Reservations page
    "reservations.manage": "قم بإدارة حجوزاتك وتتبع حالة خدماتك",
    "reservations.filters.all": "الكل",
    "reservations.filters.pending": "قيد الانتظار",
    "reservations.filters.confirmed": "مؤكدة",
    "reservations.filters.completed": "منتهية",
    "reservations.status.confirmed": "مؤكدة",
    "reservations.status.pending": "قيد الانتظار",
    "reservations.status.completed": "منتهية",
    "reservations.contact": "اتصل",
    "reservations.details": "عرض التفاصيل",
    "reservations.empty.title": "لا توجد حجوزات",
    "reservations.empty.desc": "ليس لديك أي حجوزات بعد. ابدأ بالبحث عن خدمة!",
    "reservations.empty.cta": "ابحث عن خدمة",

    // Favorites page
    "favorites.description": "مقدمو الخدمات المفضلون لديك والخدمات التي تحبها",
    "favorites.stats.total": "إجمالي المفضلة",
    "favorites.stats.online": "متصل",
    "favorites.stats.club_pro": "نادي المحترفين",
    "favorites.message": "رسالة",
    "favorites.call": "اتصال",
    "favorites.empty.title": "لا توجد مفضلة",
    "favorites.empty.desc": "لم تقم بإضافة أي مقدمي خدمات إلى المفضلة بعد. ابدأ باستكشاف خدماتنا!",
    "favorites.empty.cta": "اكتشف مقدمي الخدمات",

    // Messages page
    "messages.search_placeholder": "ابحث...",
    "messages.just_now": "الآن",

    // Settings page
    "settings.title": "الإعدادات",
    "settings.description": "إدارة تفضيلاتك وإعدادات الحساب",
    "settings.profile_section": "الملف الشخصي والمعلومات",
    "settings.profile.personal": "المعلومات الشخصية",
    "settings.profile.avatar": "الصورة الرمزية والصورة",
    "settings.profile.language": "تفضيلات اللغة",
    "settings.security_section": "الأمان والوصول",
    "settings.security.password": "كلمة المرور",
    "settings.security.2fa": "المصادقة الثنائية",
    "settings.security.sessions": "الجلسات النشطة",
    "settings.notifications_section": "الإشعارات",
    "settings.notifications.manage": "إعدادات الإشعارات",
    "settings.notifications.email": "البريد الإلكتروني",
    "settings.notifications.sms": "رسائل SMS",
    "settings.notifications.push": "إشعارات دفع",
    "settings.theme.dark_mode": "الوضع الداكن",
    "settings.actions.logout": "تسجيل الخروج",
    "settings.actions.delete_account": "حذف الحساب",
    "settings.actions.export_data": "تصدير البيانات",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("fr");

  useEffect(() => {
    const savedLanguage = localStorage.getItem("khadamat-language") as Language;
    if (savedLanguage && (savedLanguage === "fr" || savedLanguage === "ar")) {
      setLanguage(savedLanguage);
    }
  }, []);

  useEffect(() => {
    localStorage.setItem("khadamat-language", language);
    document.documentElement.dir = language === "ar" ? "rtl" : "ltr";
    document.documentElement.lang = language;
    
    if (language === "ar") {
      document.documentElement.classList.add("rtl");
    } else {
      document.documentElement.classList.remove("rtl");
    }
  }, [language]);

  const toggleLanguage = () => {
    setLanguage(prev => prev === "fr" ? "ar" : "fr");
  };

  const t = (key: string, options?: { count?: number; formattedCount?: string }): string => {
    const translation = translations[language][key];
    if (!translation) return key;
    if (typeof translation === "object" && options?.count !== undefined) {
      const pluralForm = new Intl.PluralRules(language).select(options.count);
      const template = translation[pluralForm] || translation.other;
      const countStr =
        options.formattedCount ?? new Intl.NumberFormat(language).format(options.count);
      return template.replace("{{count}}", countStr);
    }
    if (typeof translation === "string") {
      if (options?.count !== undefined) {
        const countStr =
          options.formattedCount ?? new Intl.NumberFormat(language).format(options.count);
        return translation.replace("{{count}}", countStr);
      }
      return translation;
    }
    return key;
  };

  const isRTL = language === "ar";

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
