export const env = {
  port: parseInt(process.env.PORT || '3000', 10),
  frontendUrl: process.env.FRONTEND_URL || '*',
  databaseUrl: process.env.DATABASE_URL || '',
  jwtSecret: process.env.JWT_SECRET || '',
  stripePublicKey: process.env.STRIPE_PUBLIC_KEY || '',
  stripeSecretKey: process.env.STRIPE_SECRET_KEY || '',
  stripeWebhookSecret: process.env.STRIPE_WEBHOOK_SECRET || '',
  stripePriceId: process.env.STRIPE_PRICE_ID,
  currency: process.env.CURRENCY || 'mad',
  logLevel: process.env.LOG_LEVEL || 'info',
  sentryDsn: process.env.SENTRY_DSN || '',
  redisUrl: process.env.REDIS_URL,
  healthReadyDelayMs: parseInt(process.env.HEALTH_READY_DELAY_MS || '0', 10),
  appVersion: process.env.APP_VERSION || '0.0.0',
  forceOnline: process.env.FORCE_ONLINE === 'true',
  offlineMode: process.env.OFFLINE_MODE === 'true',
  offlineSkipTests: process.env.OFFLINE_SKIP_TESTS === 'true',
  productionOfflineAllowed: process.env.PRODUCTION_OFFLINE_ALLOWED === 'true',
  searchRadiusKm: Math.min(100, Math.max(5, parseInt(process.env.SEARCH_RADIUS_KM || '30', 10))),
  searchRanking: process.env.SEARCH_RANKING === 'text_first' ? 'text_first' : 'popularity_local',
  piiRetentionDays: parseInt(process.env.PII_RETENTION_DAYS || '365', 10),
  piiExportMaxMb: parseInt(process.env.PII_EXPORT_MAX_MB || '10', 10),
  piiExportFormat: process.env.PII_EXPORT_FORMAT || 'json',
  piiExportRatePerDay: parseInt(process.env.PII_EXPORT_RATE_PER_DAY || '3', 10),
  prismaEnginesMirror: process.env.PRISMA_ENGINES_MIRROR || 'https://binaries.prisma.sh/all',
  prismaEnginesChecksumIgnore: process.env.PRISMA_ENGINES_CHECKSUM_IGNORE === 'true',
  stripeIdentityWebhookSecret: process.env.STRIPE_IDENTITY_WEBHOOK_SECRET || '',
  adminIpAllowlist: process.env.ADMIN_IP_ALLOWLIST || '',
  trustProxy: process.env.TRUST_PROXY === 'true',
  cookieSecure: process.env.COOKIE_SECURE === 'true',
  cookieSameSite: (process.env.COOKIE_SAMESITE || 'lax') as 'lax' | 'strict' | 'none',
  smsQuietStart: process.env.SMS_QUIET_START || '21:00',
  smsQuietEnd: process.env.SMS_QUIET_END || '08:00',
  smsMaxRetries: parseInt(process.env.SMS_MAX_RETRIES || '3', 10),
  smsRetryBackoffMs: parseInt(process.env.SMS_RETRY_BACKOFF_MS || '60000', 10),
  cacheTtlSeconds: parseInt(process.env.CACHE_TTL_SECONDS || '600', 10),
  rateGlobalWindowMin: parseInt(process.env.RATE_GLOBAL_WINDOW_MIN || '1', 10),
  rateGlobalMax: parseInt(process.env.RATE_GLOBAL_MAX || '120', 10),
  authMaxFailedLogins: parseInt(process.env.AUTH_MAX_FAILED_LOGINS || '7', 10),
  authLockoutMinutes: parseInt(process.env.AUTH_LOCKOUT_MINUTES || '30', 10),
  metricsEnabled: process.env.METRICS_ENABLED === 'true',
  metricsToken: process.env.METRICS_TOKEN || '',
  metricsBucketsMs: (process.env.METRICS_BUCKETS_MS || '25,50,100,250,500,1000,2000')
    .split(',')
    .map((v) => parseInt(v, 10))
    .filter((v) => !isNaN(v)),
  i18nDefaultLang: process.env.I18N_DEFAULT_LANG || 'fr',
  notifDefaultEmail: (process.env.NOTIF_DEFAULT_EMAIL ?? 'true') === 'true',
  notifDefaultSms: (process.env.NOTIF_DEFAULT_SMS ?? 'true') === 'true',
  notifDefaultPush: (process.env.NOTIF_DEFAULT_PUSH ?? 'false') === 'true',
  smtpHost: process.env.SMTP_HOST || '',
  smtpPort: parseInt(process.env.SMTP_PORT || '587', 10),
  smtpUser: process.env.SMTP_USER || '',
  smtpPass: process.env.SMTP_PASS || '',
  smtpSecure: process.env.SMTP_SECURE === 'true',
  smtpFrom: process.env.SMTP_FROM || 'Khadamat <no-reply@khadamat.ma>',
  emailEnabled: (process.env.EMAIL_ENABLED ?? 'true') === 'true',
  backupEnabled: (process.env.BACKUP_ENABLED ?? 'true') === 'true',
  backupDir: process.env.BACKUP_DIR || './backups',
  backupRetentionDays: parseInt(process.env.BACKUP_RETENTION_DAYS || '14', 10),
};
